// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbsRtzfRTmaaoBL0XOoD0Vfo1hH0A16wA',
    appId: '1:189620420007:web:155770dee283f29d150a82',
    messagingSenderId: '189620420007',
    projectId: 'btlandroid-b2319',
    authDomain: 'btlandroid-b2319.firebaseapp.com',
    storageBucket: 'btlandroid-b2319.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbsRtzfRTmaaoBL0XOoD0Vfo1hH0A16wA',
    appId: '1:189620420007:android:a9915a5a5bb5bc09150a82',
    messagingSenderId: '189620420007',
    projectId: 'btlandroid-b2319',
    storageBucket: 'btlandroid-b2319.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbsRtzfRTmaaoBL0XOoD0Vfo1hH0A16wA',
    appId: '1:189620420007:ios:your_ios_app_id',
    messagingSenderId: '189620420007',
    projectId: 'btlandroid-b2319',
    storageBucket: 'btlandroid-b2319.firebasestorage.app',
    iosBundleId: 'com.example.tluFaceAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbsRtzfRTmaaoBL0XOoD0Vfo1hH0A16wA',
    appId: '1:189620420007:ios:your_macos_app_id',
    messagingSenderId: '189620420007',
    projectId: 'btlandroid-b2319',
    storageBucket: 'btlandroid-b2319.firebasestorage.app',
    iosBundleId: 'com.example.tluFaceAttendance',
  );
}